### ISSUE TITLE
Version 1 Roadmap

### ISSUE THREAD

**Issue by scott-ainsworth** [scott-ainsworth/avahi-aliases-rs#13]
#### `avahi-alias` Command Line Utility Requirements
- [x] Add, remove, and list aliases (`avahi-alias` command).
- [x] Ignore comments and extraneous whitespace in aliases files.
- [x] Overhaul error:ErrorWrapper to minimize borrows. #15
- [x] Validate aliases. #14

#### `avahi-alias-daemon` Requirements
- [x] Overview: #6
- [x] Operate at the command line.
- [x] Operate under *systemd*.
- [x] Log to *syslog* if requested. #12
- [x] Poll for alias file changes (vice hooking to file system change events).
- [x] Specify polling interval (`--poll-time` option, default: 5 sec.). #36

#### Common requirements
- [x] Write `README.md`. #1
- [x] Specify the alias file to use (`--file` option, default: /etc/avahi/avahi-aliases)
- [x] Specify the level of verbosity (`--verbose` option *or* `--quiet` option, default: false)
- [x] Specify debug-level logging (`--debug` option, default: false)

**Comment by scott-ainsworth** [comment]
Version 1.0 released.
