### ISSUE TITLE
Version 1.1 Roadmap

### ISSUE THREAD

**Issue by scott-ainsworth** [scott-ainsworth/avahi-aliases-rs#48]
**Functionality**

- [ ] Encode IDNA names #24
- [ ] Follow Avahi publishing guidelines #30
- [x] Add `--ttl` option to the daemon #46
- [x] Add `--timeout` options to the daemon #47
- [x] General housekeeping #51
- [x] Add integration test for `avahi-alias` #53
- [x] Validate `--poling-interval, `--timeout`, and `--ttl` #56
- [ ] Upgrade third-party packages #58
- [x] Cleanup lints #59

**Process and Delivery**
 - [x] Implement GitHub actions to verify pull requests #26
 - [ ] Implement GitHub actions to create releases
